### ISSUE TITLE
ValueError: could not broadcast input array from shape (8,40) into shape (6,40)

### ISSUE THREAD

**Issue by SeekPoint** [vendi12/MemN2N-tableQA#2]
python tableQA_runner.py 
Dictionary: 2102
Number of training examples 12618
1 | train error: 0.948842 | val error: 0.909884                 
2 | train error: 0.866989 | val error: 0.902616                 
。。。。。             
100 | train error: 0.161009 | val error: 0.805959               
Number of testing examples 3973
Traceback (most recent call last):
  File "tableQA_runner.py", line 65, in <module>
    run_tableQA(data_path, './trained_model/memn2n_table_qa_model_%s.pklz' % dataset)
  File "tableQA_runner.py", line 48, in run_tableQA
    test(test_story, test_questions, test_qstory, memory, model, loss, general_config)
  File "/Users/MemN2N-tableQA/train_test.py", line 204, in test
    memory[0].data[:d.shape[0], :d.shape[1], b] = d
ValueError: could not broadcast input array from shape (8,40) into shape (6,40)
186590cc37a5:MemN2N-tableQA $

**Comment by adamliuio** [comment]
Hi @vendi12, I am experiencing the same error as well. Do you have any advice on how to look into it?

The last part of the error looks like this:

```
97 | train error: 0.169496 | val error: 0.805233
98 | train error: 0.167751 | val error: 0.805959
99 | train error: 0.167116 | val error: 0.805959
100 | train error: 0.161247 | val error: 0.805959
Number of testing examples 3973
Traceback (most recent call last):
  File "tableQA_runner.py", line 65, in <module>
    run_tableQA(data_path, './trained_model/memn2n_table_qa_model_%s.pklz' % dataset)
  File "tableQA_runner.py", line 48, in run_tableQA
    test(test_story, test_questions, test_qstory, memory, model, loss, general_config)
  File "/home/ubuntu/BI_AI/MemN2N_tableQA/train_test.py", line 204, in test
    memory[0].data[:d.shape[0], :d.shape[1], b] = d
ValueError: could not broadcast input array from shape (8,40) into shape (6,40)
```

I've spent many hours trying to figure it out but still couldn't. So if you can give a hand that would be really helpful.

Thanks.

**Comment by svakulenk0** [comment]
Hi! Sorry for the late reply! had to finish up a few other projects.
I have experimented with different datasets, just reverted to the one that I trained the model on originally. It should work now) Let me know if it helped!

Thanks for reporting!
Sveta

**Comment by adamliuio** [comment]
Hi @vendi12,

Thanks for updating, I just tried the updated code, it is working now.

What kind of instances are you using?

Because when trying to use `demo/qa.py`, I got error as below:

```
ubuntu@monsta:~/BI_AI/MemN2N-tableQA$ python2.7 -m demo.qa
Loading word embeddings model
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/BI_AI/MemN2N-tableQA/demo/qa.py", line 445, in <module>
    run_web_demo(args.data_dir, args.model_file)
  File "/home/ubuntu/BI_AI/MemN2N-tableQA/demo/qa.py", line 417, in run_web_demo
    webapp.init(data_dir, model_file)
  File "demo/web/webapp.py", line 21, in init
    memn2n = MemN2N(data_dir, model_file)
  File "demo/qa.py", line 44, in __init__
    self.word_model = fasttext.load_model(EMBEDDINGS_MODEL_PATH)
  File "fasttext/fasttext.pyx", line 154, in fasttext.fasttext.load_model
Exception: fastText: Cannot load ../fastText/result/fil9.bin due to C++ extension failed to allocate the memory
```

I experienced it a while ago when I was playing around with fastText, but didn't find the answer. Seems like it might because of the new version of fastText.

Did you experience this error?

Thanks.

**Comment by SeekPoint** [comment]
it works
